exclude: 'bin/.*|Data/.*|DataFIX/.*|DataFix/.*|packages/.*|library/.*|Images/.*|.*.proj'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-case-conflict
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']
    exclude: '.*\.bat$'
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: trailing-whitespace
    exclude: '.*\.bat$'
#- repo: https://github.com/yoheimuta/protolint
#  rev: v0.42.2
#  hooks:
#  - id: protolint
#- repo: https://github.com/pre-commit/mirrors-clang-format
#  rev: "b111689e7b5cba60be3c62d5db2bd1357f4d36ca"
#  hooks:
#  - id: clang-format
#    types_or: [c#]
